---
title: "Title"
author: "Avishai Wizel"
date: '`r Sys.Date()`'
output: 
  html_notebook: 
    code_folding: hide
---

## Data

```{r}
acc = readRDS(file = data_to_read)
pathways_scores = fread(file = "./Data/ACC_Canonical_Pathway_Scores.txt",sep = ",") %>% as.matrix(rownames=1) %>% t() %>%  as.data.frame()
```


```{r}
#adjust pathways_scores:
pathways_scores[340] <- NULL #Remove NA col
pathways_scores = pathways_scores [rownames(pathways_scores) %in% colnames(acc),] #remove cells not in dataset
pathways_scores =  pathways_scores[order(row.names(pathways_scores)),] #order cells like dataset
```

```{r warning=FALSE}
pathway_scores_assay <- CreateAssayObject(counts = pathways_scores %>% t()) #create an assay
```

```{r warning=FALSE}
acc[["pathway_scores"]] = pathway_scores_assay
```

```{r warning=FALSE, results='hide',echo=TRUE}
# run-dim-reduction:
acc <- FindVariableFeatures(acc, selection.method = "vst", nfeatures = 1000,assay = "pathway_scores")
acc <- ScaleData(acc,assay = "pathway_scores",features = rownames(acc[["pathway_scores"]]))
acc <- RunPCA(acc, features = rownames(acc[["pathway_scores"]]),assay = "pathway_scores")
```

```{r}
#set lum_or_myo metadata
luminal_over_myo = FetchData(object = acc,vars = "luminal_over_myo")
luminal_over_myo$lum_or_myo  = case_when(luminal_over_myo$luminal_over_myo >1~"lum",luminal_over_myo$luminal_over_myo <(-1)~"myo",TRUE~"NA")
luminal_over_myo$luminal_over_myo <-NULL
acc=AddMetaData(object = acc,metadata = luminal_over_myo,col.name = "lum_or_myo")
```



```{r}
acc_noNA = subset(x = acc,subset = (lum_or_myo != "NA"))
```
## Results {.tabset}

```{r results='asis',echo=TRUE}
for (i in 1:6) {
  cat("###",i," \n")
  print(DimPlot(object = acc_noNA,reduction = "pca",group.by = "lum_or_myo",dims = c(1,i)))
 # hist(mtcars$mpg)
  cat(' \n\n')
plot.new()
}
  cat('## {-}') 

```
## New

```{r}
DimPlot(object = acc_noNA,reduction = "pca",group.by = "lum_or_myo",dims = c(1,i))
```


```{r}
DimPlot(object = acc_noNA,reduction = "pca",group.by = "lum_or_myo",dims = c(1,2))
```
```{r}
DimPlot(object = acc_noNA,reduction = "pca",group.by = "lum_or_myo",dims = c(1,3))
```
```{r}
DimPlot(object = acc_noNA,reduction = "pca",group.by = "lum_or_myo",dims = c(1,4))
```
```{r}
DimPlot(object = acc_noNA,reduction = "pca",group.by = "lum_or_myo",dims = c(2,5))
```
```{r}
DimPlot(object = acc,reduction = "pca",group.by = "lum_or_myo",dims = c(1,6))
```

```{r fig.height=10, fig.width=10}
print(acc[["pca"]], dims = 5, nfeatures = 5)
VizDimLoadings(acc, dims = 5, reduction = "pca")
```
```{r}
luminal_pathways = fread(file = "./Data/ACC_BREAST_CANCER_MIX_Pathway_Scores.txt",sep = ",") %>% as.matrix(rownames=1) %>% t() %>%  as.data.frame()
```





```{r}
#adjust pathways_scores:
pathways_scores[340] <- NULL #Remove NA col
pathways_scores = pathways_scores [rownames(pathways_scores) %in% colnames(acc),] #remove cells not in dataset
pathways_scores =  pathways_scores[order(row.names(pathways_scores)),] #order cells like dataset
```
