---
title: "Title"
author: "Avishai Wizel"
date: '`r Sys.Date()`'
output: 
  html_notebook: 
    code_folding: hide
    toc: yes
    toc_collapse: yes
    toc_float: 
      collapsed: FALSE
---

## Parameters

```{r warning=FALSE}
suffix = "HallmarksAndLum_genesPCA"
data_to_read = "./Data/acc_cancer_no146_primaryonly15k_cancercells.rds"
```


## functions

```{r warning=FALSE}
```
```{r}
file_path ="/sci/labs/yotamd/lab_share/avishai.wizel/R_projects/ACC_pathway_scores/Notebooks/Clustering_HallmarksAndLum.html"
pandoc_convert(file_path, to = "markdown_strict",output = "test.md")
```

## Data

```{r eval=TRUE, include=TRUE}
acc = readRDS(file = data_to_read)
(message("reading '" %>% paste0(data_to_read %>% basename()) %>% paste0("'")))
pathways_scores = fread(file = "./Data/ACC_Hallmark_Pathway_Scores.txt",sep = ",") %>% as.matrix(rownames=1) %>% t() %>%  as.data.frame()
luminal_scores = fread(file = "./Data/ACC_BREAST_CANCER_MIX_Pathway_Scores.txt",sep = ",") %>% as.matrix(rownames=1) %>% t() %>%  as.data.frame()

```
```{r}
#set lum_or_myo metadata
luminal_over_myo = FetchData(object = acc,vars = "luminal_over_myo")
luminal_over_myo$lum_or_myo  = case_when(luminal_over_myo$luminal_over_myo >1~"lum",luminal_over_myo$luminal_over_myo <(-1)~"myo",TRUE~"NA")
luminal_over_myo$luminal_over_myo <-NULL
acc=AddMetaData(object = acc,metadata = luminal_over_myo,col.name = "lum_or_myo")
```


```{r}
acc_noNA = subset(x = acc,subset = (lum_or_myo != "NA"))
```
# PCA with genes

## ALL PC's {.tabset}
```{r results='asis',echo=TRUE}
for (i in 1:8) {
  cat("### PC",i," \n")
  print(DimPlot(object = acc_noNA,reduction = "pca",group.by = "lum_or_myo",dims = c(i,i),pt.size = 0.5))
  cat(' \n\n')
  plot.new()
}

```

## PC1 top pathways
```{r fig.height=10, fig.width=10}
VizDimLoadings(acc, dims = 1, reduction = "pca")
```
# PCA with pathway scores
```{r}
pathways_scores = cbind(pathways_scores,luminal_scores)
pathways_scores = pathways_scores[ , colSums(is.na(pathways_scores))==0] #remove cols with NA
```

```{r}
#adjust pathways_scores:
pathways_scores = pathways_scores[ , colSums(is.na(pathways_scores))==0] #remove cols with NA
pathways_scores = pathways_scores [rownames(pathways_scores) %in% colnames(acc),] #remove cells not in dataset
pathways_scores =  pathways_scores[order(row.names(pathways_scores)),] #order cells like dataset
```

```{r warning=FALSE}
pathway_scores_assay <- CreateAssayObject(counts = pathways_scores %>% t()) #create an assay
```

```{r warning=FALSE}
acc[["pathway_scores"]] = pathway_scores_assay
```

```{r warning=FALSE, results='hide',echo=TRUE}
# run-dim-reduction:
acc <- FindVariableFeatures(acc, selection.method = "vst", nfeatures = 1000,assay = "pathway_scores")
acc <- ScaleData(acc,assay = "pathway_scores",features = rownames(acc[["pathway_scores"]]))
acc <- RunPCA(acc, features = rownames(acc[["pathway_scores"]]),assay = "pathway_scores")
```

```{r}
#set lum_or_myo metadata
luminal_over_myo = FetchData(object = acc,vars = "luminal_over_myo")
luminal_over_myo$lum_or_myo  = case_when(luminal_over_myo$luminal_over_myo >1~"lum",luminal_over_myo$luminal_over_myo <(-1)~"myo",TRUE~"NA")
luminal_over_myo$luminal_over_myo <-NULL
acc=AddMetaData(object = acc,metadata = luminal_over_myo,col.name = "lum_or_myo")
```


```{r}
acc_noNA = subset(x = acc,subset = (lum_or_myo != "NA"))
```


## All PC's {.tabset}
```{r results='asis',echo=TRUE}
for (i in 1:8) {
  cat("### PC",i," \n")
  print(DimPlot(object = acc_noNA,reduction = "pca",group.by = "lum_or_myo",dims = c(1,i)))
  cat(' \n\n')
  plot.new()
}

```


## PC4 top pathways
```{r fig.height=10, fig.width=10}
VizDimLoadings(acc, dims = 4, reduction = "pca")
```

## Pathways on UMAP
```{r}
pathway = pathways_scores[,"CHARAFE_BREAST_CANCER_LUMINAL_VS_MESENCHYMAL_DN",drop=F]
acc = AddMetaData(object = acc,metadata = pathway)
```

```{r}
FeaturePlot(object = acc, features = "CHARAFE_BREAST_CANCER_LUMINAL_VS_MESENCHYMAL_DN",max.cutoff = 0.3)
```

```{r}
pathway = pathways_scores[,"HUPER_BREAST_BASAL_VS_LUMINAL_DN",drop=F]
acc = AddMetaData(object = acc,metadata = pathway)
```

```{r}
FeaturePlot(object = acc, features = "HUPER_BREAST_BASAL_VS_LUMINAL_DN")
```